### ISSUE TITLE
Can't see progress bar in the volume bar

### ISSUE THREAD

**Issue by Stup0r38** [WillPower3309/awesome-dotfiles#15]
When the volume is changed i can only see the the place where the progress bar should be, but not the progress bar itself
![Schermata del 2020-06-23 19-34-53](https://user-images.githubusercontent.com/65513091/85436210-f17e7e00-b588-11ea-8ba6-66b470635961.png)

**Comment by Stup0r38** [comment]
Update:
I know mine is a different configuration, just tried to use yours and the problem is still there
![Schermata del 2020-06-24 08-39-05](https://user-images.githubusercontent.com/65513091/85509419-473d3f80-b5f6-11ea-9fb8-194512012abf.png)

**Comment by WillPower3309** [comment]
Hmm, allow me to investigate! Is sound working on your system in general?

**Comment by Stup0r38** [comment]
Yes, sound works and if I try to change the volume it works, but the progress bar doesn't appear

**Comment by WillPower3309** [comment]
Does the command `amixer` work on your computer? I think I missed adding that as a dependency

**Comment by WillPower3309** [comment]
Also, you will want to keep an eye on my repo for the next few days, as the volume bar occasionally lags and I am currently working on a fix. I will be also adding a brightness bar

**Comment by Stup0r38** [comment]
Just tried amixer command, it works.

Also tried
`amixer sget Master | grep 'Right:' | awk -F '[][]' '{print $2}'| sed 's/[^0-9]//g'`
and it shows the correct volume.


I will keep an eye on the repo for sure, it's an amazing project!

**Comment by Stup0r38** [comment]
I don't know if it's important, but I'm using Fedora 32

**Comment by WillPower3309** [comment]
Okay thanks! I'll investigate this evening. I'm glad you like it!

**Comment by WillPower3309** [comment]
Hey man, can you confirm you're running the latest version? I had similar issues the other day, however if you pulled within the last ~24 hours you should be on the latest version which means I'll need to investigate more closely

**Comment by WillPower3309** [comment]
Going to try to recreate this, what version of awesome are you running? (you can check with `awesome --version`)

**Comment by Stup0r38** [comment]
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**Comment by WillPower3309** [comment]
@Stup0r38 mind sending the output of `amixer sget Master | grep 'Right:' | awk -F '[][]' '{print $2}'| sed 's/[^0-9]//g'`?

**Comment by Stup0r38** [comment]
95 (it's the right volume)

**Comment by Stup0r38** [comment]
Update:
I just tried using your config on two vm, one with Fedora and the other with Manjaro, in both the vm I had the same problem, maybe there is some other dependency needed?

**Comment by WillPower3309** [comment]
> Update:
> I just tried using your config on two vm, one with Fedora and the other with Manjaro, in both the vm I had the same problem, maybe there is some other dependency needed?

Thats good information, thanks! Ill try on a couple other distros and see if I can isolate it. Its strange since the only dependency should (in theory) be amixer / alsamixer

**Comment by BaDxKaRMa** [comment]
I'm having the same issue with a new Arch install. I had to modify the amixer sget grep command to "Mono" from "Right". The command outputs the right value (my volume does change), but the widget has no volume bar. If I change the default value to something other than 0, I see the bar for a moment but once the value updates the bar goes away like in the screenshot. 

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**Comment by WillPower3309** [comment]
Thanks for the info, I'll take another crack at fixing this shortly. I think I have some ideas as to what it may be :)

**Comment by WillPower3309** [comment]
Just wanted to let you guys know I'm still investigating this, past week has been very busy but I'm aiming to finish this and make a few more optimizations to the codebase, hoping to work on a new theme soon.

**Comment by Ball-Man** [comment]
I've been struggling this problem too(actually, I've had this for months). I personally fixed it, but I accidentally pulled your most recent commit deleting all my work. I don't remember exactly what the problem was, but it was definitely something with how the template gets the volume(the amixer command or whatever).
I also have a slight problem with the power supply indicator(maybe I should open an issue on its own for this).

Here are my specs:
awesome v4.3-684-g2f905f252 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

OS: Arch Linux x86_64 
Kernel: 5.7.10-arch1-1 
Resolution: 1920x1080 
WM: awesome  
CPU: Intel i5-6200U (4) @ 2.800GHz 
GPU: Intel Skylake GT2 [HD Graphics 520]

**Comment by WillPower3309** [comment]
> I've been struggling this problem too(actually, I've had this for months). I personally fixed it, but I accidentally pulled your most recent commit deleting all my work. I don't remember exactly what the problem was, but it was definitely something with how the template gets the volume(the amixer command or whatever).
> I also have a slight problem with the power supply indicator(maybe I should open an issue on its own for this).
> 
> Here are my specs:
> awesome v4.3-684-g2f905f252 (Too long)
> • Compiled against Lua 5.3.5 (running with Lua 5.3)
> • D-Bus support: yes
> • xcb-errors support: no
> • execinfo support: yes
> • xcb-randr version: 1.6
> • LGI version: 0.9.2
> 
> OS: Arch Linux x86_64
> Kernel: 5.7.10-arch1-1
> Resolution: 1920x1080
> WM: awesome
> CPU: Intel i5-6200U (4) @ 2.800GHz
> GPU: Intel Skylake GT2 [HD Graphics 520]

If you could throw this into a separate issue with a brief summary of what the power supply indicator issue is I'd be very appreciative, thanks! And if you happen to recall your fix please also let me know, I'm setting up an array of vms at the moment with different OSes / configurations to hopefully avoid this in the future:)

**Comment by Ball-Man** [comment]
> If you could throw this into a separate issue with a brief summary of what the power supply indicator issue is I'd be very appreciative, thanks! And if you happen to recall your fix please also let me know, I'm setting up an array of VMs at the moment with different OSes / configurations to hopefully avoid this in the future:)

Sure. I suppose the real problem is that my fix was/is probably very specific to my machine/configuration, but hopefully we can cover all edge cases with a bit of work. I will probably instantiate the new issue tomorrow, thank you for your kindness

**Comment by ilthraim** [comment]
I fixed this by changing line 86 of volume-adjust.lua to `volume_bar.value = tonumber(stdout)`

**Comment by Stup0r38** [comment]
Thanks, it gives me some minor problems, but it's definately and improvement. Thanks

**Comment by BaDxKaRMa** [comment]
I made this change and my bar does not work still. Before the change the bar goes missing (just the smaller bar in the bubble), and after the bar stays but it is black. I don't seem to have any scaling issues though.  

Actually, I just found my issue looking in this file. `amixer sget Master | grep 'Mono:' | awk -F '[][]' '{print $2}'| sed 's/[^0-9]//g'` That command was outputting a null value because Mono has no value. If I change it to Left or Right it works.

This is my output. 
 ~/.c/a/components  amixer sget Master                                                                1.6m  2020-08-13 12:04
Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 65536 [100%] [on]
  Front Right: Playback 65536 [100%] [on]

**Comment by WillPower3309** [comment]
@ilthraim awesome! Ill fix the height scaling and incorporate your fix into a merge tonight

**Comment by WillPower3309** [comment]
> I fixed this by changing line 86 of volume-adjust.lua to `volume_bar.value = tonumber(stdout)`, although I'm now having strange bar height scaling issues

Hey! Mind providing a screenshot of the scaling issues? Havent been able to identify any with the change

**Comment by WillPower3309** [comment]
Just committed the suggested line change, please let me know if this fixed your issues and I will close this issue :)

**Comment by ilthraim** [comment]
The scaling was actually just a byproduct of me switching from an alsa to pulse audio backend in the config. The commit fixed the issue!
