### ISSUE TITLE
Multimonitor Setup

### ISSUE THREAD

**Issue by Joelangelo** [WillPower3309/awesome-dotfiles#18]
Hi there, first i would like to say that i love your work!

I've been running your setup on my laptop for a while now and thought it was time to get it on my desktop PC as well. The problem I'm facing now is that only one of my monitors are working. How and where do i enable multi monitor setup? 

I am fairly new to linux over all and if you need some input just tell me what to enter :D

**Comment by WillPower3309** [comment]
Thanks, I'm happy you're enjoying it! I actually only use it on a single monitor setup for the time being, it had been working well on multi monitor, however I have since made a lot of changes to it. I'll investigate it this weekend when I am able to head to my campus apartment and use dual monitors! is the secondary monitor just blank?

**Comment by Joelangelo** [comment]
No problem, take your time!

I got the second monitor to work by using the mons command from terminal. But before that the monitor was just black yes.

**Comment by WillPower3309** [comment]
@Joelangelo a tool I'm experimenting with that you might be interested in is ARandR

Here's a link to a discussion about it: https://www.reddit.com/r/linux/comments/j19iq1/musthave_for_people_with_multimonitor_setup_arandr/?utm_medium=android_app&utm_source=share

Once I have my second monitor configured properly I'll implement some changes to better support more monitors in my config.

**Comment by WillPower3309** [comment]
Theme is now much more multi monitor friendly on the mirage_theme branch (which will be merged soon), fixed a ton of bugs and adjusted config behavior to work on any amount of monitors. You'll still need to make sure monitors are added via xrandr / arandr, however once they're recognized they will work well with the config.
