### ISSUE TITLE
Bug: Panels disappear on other tags when a client is fullscreen

### ISSUE THREAD

**Issue by WillPower3309** [WillPower3309/awesome-dotfiles#19]

**Comment by Stup0r38** [comment]
I had this bug after you changed something in top-panel.lua, check my dotfiles for the fix. 
Now I don't remember how I did it

**Comment by WillPower3309** [comment]
> I had this bug after you changed something in top-panel.lua, check my dotfiles for the fix. 
> Now I don't remember how I did it
> 

Thanks! I was trying to simplify my hide functionality and removed some good code! I'll take a look

**Comment by WillPower3309** [comment]
Fixed
