### ISSUE TITLE
Weird font in alacritty terminal.

### ISSUE THREAD

**Issue by Valleriite** [WillPower3309/awesome-dotfiles#21]
Some letters are closer to the other letter and someones appear further from them.
Hope you understand me,
have a nice day.

**Comment by WillPower3309** [comment]
I do! Have you installed the MesloLGS font?

[download from here](https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf), and move it into your /usr/share/fonts directory if you havent already

**Comment by Valleriite** [comment]
ok thanks will try it and report back later

**Comment by Valleriite** [comment]
thanks it worked!
