### ISSUE TITLE
The left panel looks different from the screenshot in the readme file.

### ISSUE THREAD

**Issue by Valleriite** [WillPower3309/awesome-dotfiles#23]
The left panel looks different from the screenshot in the readme file,
here is a screenshot:
![Screenshot_2020-09-28_13-52-52](https://user-images.githubusercontent.com/68468004/94434917-62d65a00-0192-11eb-9f9d-ecca5a7e39b6.png)
I don't think I modified the config for it.
Thanks for reading,
Have a nice day

**Comment by Valleriite** [comment]
Managed to get it fixed by using the pastel theme from the "new_theme" branch(if anyone wants to do it just paste this to the terminal `git clone --branch new_theme https://github.com/WillPower3309/awesome-dotfiles/`a folder named awesome-dotfiles should appear at your home folder (note: git should be installed, just google how to install git Linux) go inside the folder and copy the content of the pastel colder and paste it in the .config folder(show hidden files should be enabled in the file manager(just google how to enable hidden files in your distribution))) and using the max layout (changed at the top right)

**Comment by Valleriite** [comment]
I think if you have a larger screen than mine you won't need to enable the max layout

**Comment by WillPower3309** [comment]
Thanks for the comment, you can also adjust the length of the left panel by changing the height on line 46 of `awesome/components/left-panel.lua`

**Comment by Valleriite** [comment]
Not even sure if you need to use the new_theme branch,
I may have been just stupid,
to anyone reading this,
maybe use the master branch and enable the max layout, if the issue stays, use the instructions I stated before.

**Comment by Valleriite** [comment]
also, you are welcome,
thank YOU for these dotfiles

**Comment by Valleriite** [comment]
your response is quite a better fix

**Comment by WillPower3309** [comment]
> your response is quite a better fix

happy to help!
