### ISSUE TITLE
Keybinds not working.

### ISSUE THREAD

**Issue by slfg** [WillPower3309/awesome-dotfiles#24]
Howdy, first of all thank you for sharing the dotfile and giving good and straight foward instructions but I'm having a problem after installing the dotfiles, none of the keybinds are working for some reason except for master + esc, and because of the lack of the right click menu (there's a way to put it back in via the dotfiles?) I can't even use the terminal or any applications.

I'm using manjaro on a VM (VirtualBox), I'm testing dotfiles before I use them on my main laptop.

**Comment by WillPower3309** [comment]
Are there any error messages that pop up?

**Comment by slfg** [comment]
none, it looks totally normal at first glance.

**Comment by slfg** [comment]
update: after restarting the VM the keybinds are almost working, the terminal is not opening at all for some reason, if I press super + enter the cursor for a brief moment shows that something is loading, but nothing happens, also the applications menu only shows "..." instead of the application name.

**Comment by WillPower3309** [comment]
Are you using alacrity as your terminal? If not you need to change the terminal value in apps.lua

**Comment by slfg** [comment]
yeah that was my bad, now everything is working (maybe VirtualBox was messing with the keybinds when I installed the dotfiles, but now its working normally for some reason), thanks for the help and for the dotfiles.

**Comment by WillPower3309** [comment]
> yeah that was my bad, now everything is working (maybe VirtualBox was messing with the keybinds when I installed the dotfiles, but now its working normally for some reason), thanks for the help and for the dotfiles.

no worries, happy things are working
