### ISSUE TITLE
Workspace/tags indicator?

### ISSUE THREAD

**Issue by NeoScaler** [WillPower3309/awesome-dotfiles#3]
Hi there,

great work, theme is looking really awesome! I am missing a workspace/tags indicator, so some kind of indicator which shows on which workspaces open applications are. Am I missing it or is it not included / configured?

**Comment by WillPower3309** [comment]
Hey, that’s what the side panel does! If the background of the icon is lighter there’s a window open there, and the one you’re currently in is darker

**Comment by NeoScaler** [comment]
Ah, got it now. Can I configure the behavior that the side panel switches screens when I open applications? Seems confusing for me currently.
