### ISSUE TITLE
Picom config?

### ISSUE THREAD

**Issue by hrqmonteiro** [WillPower3309/awesome-dotfiles#35]
Hey, great config, i was off unixporn for some time but i saw now your Mirage config, very nice!

Any chance you could share your picom config? I am struggle to get the round corners properly, without showing some white squares in some edges.

If you could, would be nice! Thanks.

**Comment by WillPower3309** [comment]
https://www.github.com/WillPower3309/awesome-dotfiles/tree/master/awesome%2Fconfiguration%2Fmirage%2Fpicom.conf

Here you go!

**Comment by hrqmonteiro** [comment]
Yea i was a moron, i couldn't find it cause i looked into `~/.config` and `~/.config/picom`only, then i found it. Sorry for the trouble lol
