### ISSUE TITLE
Weird rofi issue

### ISSUE THREAD

**Issue by inzar98** [WillPower3309/awesome-dotfiles#4]
I have installed https://github.com/vinceliuice/McMojave-circle icons and sf fonts isnt that weird ? 
![2020-01-25-092542_1920x1080_scrot](https://user-images.githubusercontent.com/4786066/73119131-69526900-3f55-11ea-9ace-ff34ac708338.png)
Im using git version

Fonts and icons not showing up :(

**Comment by WillPower3309** [comment]
Hmm, that's very strange. Try opening rofi from the terminal with `rofi -normal-window -modi drun -show drun` and let me know what it says, it may be an issue with drun
