### ISSUE TITLE
Pin specific program to tags

### ISSUE THREAD

**Issue by garyniger-code** [WillPower3309/awesome-dotfiles#40]
I haven't been able to pin programs to specific tags using this setup.

I have tried setting up rules like in the vanilla rc.lua with properties = { tag = tags[1][5] } }, in rules.lua but it has no effect. Other rules are working for the program.
I believe it has to do with the non standard tag creation in the rc.lua.

Has anyone got it working?

**Comment by WillPower3309** [comment]
tags are created in `mirage.lua` or in `pastel.lua` in the awesomewm4.3 recommended way:
```
   awful.screen.connect_for_each_screen(function(s)
      for i = 1, 7, 1
      do
         awful.tag.add(i, {
            icon = icon_dir .. i .. ".png",
            icon_only = true,
            layout = awful.layout.suit.tile,
            screen = s,
            selected = i == 1
         })
      end
```

**Comment by WillPower3309** [comment]
I can look into client / tag placement though. I suspect its an awesomewm4.3 thing

**Comment by garyniger-code** [comment]
Got it figured out now.
the current way of pinning to screen 1, tag 8, is setting {screen = 1, tag = "8"}

Hopefully someone will find it useful
