### ISSUE TITLE
Make titlebar, sidebar and top-panel smaller

### ISSUE THREAD

**Issue by Uzaaft** [WillPower3309/awesome-dotfiles#43]
Hi!

Great work with the config! I am just wondering if there is a way to make the width of some of the elements smaller? I find the elements to be too big for my taste.

**Comment by WillPower3309** [comment]
Absolutely! Go to `awesome/theme/WHATEVER_THEME_YOURE_USING.lua` (i suspect mirage based on the titlebars), and lower the dpi values in:
```lua
-- Panel Sizing
theme.left_panel_width = dpi(60)
theme.top_panel_height = dpi(30)
```

For the titlebars, lower the dpi value in `awesome/components/mirage/titlebar.lua`:
```lua
   local titlebar = awful.titlebar(c, {
      size = dpi(30)
   })
```

**Comment by WillPower3309** [comment]
I'll be updating the config to have the titlebar dpi in the theme file as well, thanks for making me realize this!

**Comment by WillPower3309** [comment]
Might add a section to the README about this as well

**Comment by Uzaaft** [comment]
Sweet! Thank you for the help!

**Comment by WillPower3309** [comment]
No problem, glad I was able to help

**Comment by WillPower3309** [comment]
If the button sizing gets weird, you can change their dpi in the same awesome/components/mirage/titlebar.lua file.
