### ISSUE TITLE
sidebar icons

### ISSUE THREAD

**Issue by linde12** [WillPower3309/awesome-dotfiles#44]
What icons are you using for the pastel sidebar? I would like to add another shortcut to a folder but i want to stick to the same icon theme.

**Comment by WillPower3309** [comment]
Hey!
Here's a link to a question about the same icons from another awesomewm theme: https://github.com/elenapan/dotfiles/issues/3

**Comment by WillPower3309** [comment]
Happy to answer any unanswered questions here if you have any!

**Comment by WillPower3309** [comment]
Linebit is the name of the icon pack I used
