### ISSUE TITLE
autorun programs not autorunning

### ISSUE THREAD

**Issue by mrhappy200** [WillPower3309/awesome-dotfiles#45]
So, the autorun programs in my rc.lua just do not run. I tried changing the shell from zsh to bash, I tried replacing both the autorun list and the lua code that runs it with snippets directly from this repository. None of it worked, I also ran the commands in the terminal and they ran just fine. All the programs also used to run fine and I don't think i changed anything. Would you know what is going on?

this is my rc.lua https://pastebin.com/SYu6KMSj

Thank you,

**Comment by WillPower3309** [comment]
Which version of awesomewm are you running?

**Comment by mrhappy200** [comment]
I seem to be running awesomewm v4.3

**Comment by mrhappy200** [comment]
sorry I am late with responding but it works now, I do not know why

**Comment by WillPower3309** [comment]
No problem! If you recall changing anything to make it work let me know, but glad to hear!
