### ISSUE TITLE
I did the steps But the ui is broken 

### ISSUE THREAD

**Issue by aaryamanm128** [WillPower3309/awesome-dotfiles#50]
I had installed all the nessasary dependencies i even logged into aawesome but the problems start from there , when i Tried to click on anything it did not work no keybinnds no clicks nothing only the ui was loaded , the only thing which i could click was the callender but it was of no use

**Comment by aaryamanm128** [comment]
If im doing something wrong then please tell me how to do it or , create a shell script which helps in install of this

**Comment by WillPower3309** [comment]
Does it display any error notifications?

**Comment by aaryamanm128** [comment]
I pressed windows enter to open the terminal But it did not , then i realised that nothing was wrong , I just had not install alacritty 
, Im so sorry for wasting your time

**Comment by WillPower3309** [comment]
> I pressed windows enter to open the terminal But it did not , then i realised that nothing was wrong , I just had not install alacritty 
> , Im so sorry for wasting your time
> 

No worries at all! If anything I'm happy you opened this issue - I'll make a note in the readme about the default apps
