### ISSUE TITLE
Left Panel Functionality

### ISSUE THREAD

**Issue by BinhaoQin** [WillPower3309/awesome-dotfiles#57]
I'm a little confused about the function of left panel in Pastel theme. It seems to "store" the window launched when given icon is clicked instead of launching corresponding applications. Is this the supposed functionality of left panel? Thanks!

**Comment by WillPower3309** [comment]
Hey, hopefully this helps clear the functionality up! Although the left panel looks like a dock, it's really just a tag (or workspace) switcher. Each icon represents a different workspace (with the exception of the folders / trash icons in the pastel theme), that indicated which workspace you're currently on. Clicking one of the icons will switch you to that workspace.

**Comment by volatileAntiEntropy** [comment]
Got it, thank you very much!
