### ISSUE TITLE
Authentication Error pamac on Manjaro

### ISSUE THREAD

**Issue by lechat187** [WillPower3309/awesome-dotfiles#6]
Hi,

I am using Manjaro Awesome Community Edition. When applying your awesome theme (pun intended) everything looks great, except that pamac is not usable anymore, because authentication fails.

When reverting to my backup config and rebooting, it works again. Any ideas?

btw, a minor tweak: in your spicetify config your home is set...

Thanks for the great work!

**Comment by WillPower3309** [comment]
Hey! sorry for the late response but ill look into it!

**Comment by WillPower3309** [comment]
Hey @lechat187, try installing `lxsession` and running it before you open pamac and let me know if it solves it. Mind providing some more info on the spicetify config?

**Comment by WillPower3309** [comment]
Issue closed as as session manager such as lxsession should solve the issue, will reopen if further reports come in
