### ISSUE TITLE
get maximize minimize button in pastel

### ISSUE THREAD

**Issue by Adithyan007hack** [WillPower3309/awesome-dotfiles#63]
how can i get maximize minimize button from mirage theme in pastel 
because not a  fan of close button in top bar in pastel

**Comment by Adithyan007hack** [comment]
And plank is not working as intended 
https://www.reddit.com/r/awesomewm/comments/gh0p92/issue_with_awesome_and_plank/

one more thing how can i prioritize floating over tiling when log in

**Comment by WillPower3309** [comment]
to get titlebars: add
```lua
require("components.mirage.titlebar")
```
in (`pastel.lua`)[https://github.com/WillPower3309/awesome-dotfiles/blob/master/awesome/pastel.lua]

**Comment by WillPower3309** [comment]
To get floating by default, edit line [41 in pastel.lua](https://github.com/WillPower3309/awesome-dotfiles/blob/master/awesome/pastel.lua#L41) to be `layout = awful.layout.suit.floating,`.

**Comment by WillPower3309** [comment]
For plank, add
```lua
{
    rule_any = {
        name = {
            "plank"
        }
    },
    properties = {
        ontop = true
    }
}
```
in the `rules.create()` return block to [rules.lua](https://github.com/WillPower3309/awesome-dotfiles/blob/master/awesome/rules.lua#L49-L143)

**Comment by Adithyan007hack** [comment]
thank you so much :)
