### ISSUE TITLE
Notifications and starting up applications not working

### ISSUE THREAD

**Issue by ProkopRandacek** [WillPower3309/awesome-dotfiles#7]
I have been using these dotfiles for some while and I have never seen it make an notification window. I tried to add a copyq to startup into the code but it is not working. I don't think that this part of the code is working.

I have done some [modifications](https://github.com/ProkopRandacek/awesome-dotfiles/commit/ce533da4929968e5dd8fa442536010018049344b) but I don't think I broke it somehow.

thanks for help

**Comment by WillPower3309** [comment]
Hey! Notifications are a problem at the moment as awesome changed their API around them, I'm investigating it at the moment :)

**Comment by WillPower3309** [comment]
@ProkopRandacek fixed! Thanks for the report
