### ISSUE TITLE
problem with update brightness

### ISSUE THREAD

**Issue by nedo090** [WillPower3309/awesome-dotfiles#8]
in keys.lua there is error with the name " UpdateBriOSD "  call "UpdateBrOSD".
with this the slider move (not flowing) but gave me error in function ToggleBriOSD and ToggleVolOSD, i don't know why, with log "awesome timer not started"

**Comment by WillPower3309** [comment]
hmm, I have been having problems with the sliders, ill look into it! Thanks for the report

**Comment by WillPower3309** [comment]
Brightness widget has been temporarily removed, had similar issues with the volume slider which were fixed so when the brightness widget is readded within the next few days this will be resolved
